import { Inter } from "next/font/google";
import "./globals.css";
import { Roboto_Condensed } from "next/font/google";

const robotoCondensed = Roboto_Condensed({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
      className={`${inter.className} flex bg-gradient-to-r from-purple-50 to-pink-50`}>
      <aside className="flex flex-col w-56 p-8 fixed top-0 left-0 bottom-0 border-r-2 min-h-screen border-indigo-500">
        <h2 className="text-2xl font-bold mb-20 text-indigo-800">Dashboard</h2>
        <ul className="space-y-4">
          <li className={robotoCondensed.className}>Overview</li>
          <li className={robotoCondensed.className}>Products</li>
          <li className={robotoCondensed.className}>Transactions</li>
        </ul>
      </aside>
  
      <main className="flex-grow pl-60 p-5">
        {children}
      </main>
    </body>
  </html>
  
  );
}
